import type { Market } from './types';

const H = 3_600_000; // 1 hour in ms

export function createInitialMarkets(now: number = Date.now()): Market[] {
  return [
    {
      id: 'm1',
      title: 'India vs Australia T20 Decider — India to win?',
      description: 'Series tied 2-2. Final T20 tonight at Wankhede. India has home advantage and strong batting form.',
      type: 'binary',
      category: 'sports',
      closeTime: now + 2 * H,
      yesPool: 8_700,
      noPool: 6_300,
      outcome: null,
      predeterminedOutcome: 'yes',
      status: 'open',
      aiPrediction: 0.55,
      resolvedAt: null,
    },
    {
      id: 'm2',
      title: 'Bitcoin closes above $70,000 today?',
      description: 'BTC has been ranging between $68k–$72k this week. Bulls and bears in a standoff near key resistance.',
      type: 'binary',
      category: 'finance',
      closeTime: now + 6 * H,
      yesPool: 13_400,
      noPool: 8_600,
      outcome: null,
      predeterminedOutcome: 'yes',
      status: 'open',
      aiPrediction: 0.65,
      resolvedAt: null,
    },
    {
      id: 'm3',
      title: 'Will Kohli score 50+ in the next IPL innings?',
      description: 'RCB vs MI tonight. Kohli has been in great form but MI have a strong pace attack.',
      type: 'binary',
      category: 'sports',
      closeTime: now + 5 * H,
      yesPool: 6_200,
      noPool: 8_800,
      outcome: null,
      predeterminedOutcome: 'no',
      status: 'open',
      aiPrediction: 0.42,
      resolvedAt: null,
    },
    {
      id: 'm4',
      title: 'Nifty 50 ends positive today?',
      description: 'Indian markets opened flat. FII activity mixed. Global cues cautious ahead of US Fed minutes.',
      type: 'binary',
      category: 'finance',
      closeTime: now + 4 * H,
      yesPool: 9_800,
      noPool: 8_200,
      outcome: null,
      predeterminedOutcome: 'yes',
      status: 'open',
      aiPrediction: 0.54,
      resolvedAt: null,
    },
    {
      id: 'm5',
      title: 'Mumbai receives 5mm+ rainfall tomorrow?',
      description: 'IMD forecast shows moderate moisture in Arabian Sea. Southwest monsoon is active over Mumbai.',
      type: 'binary',
      category: 'weather',
      closeTime: now + 20 * H,
      yesPool: 3_800,
      noPool: 7_200,
      outcome: null,
      predeterminedOutcome: 'no',
      status: 'open',
      aiPrediction: 0.38,
      resolvedAt: null,
    },
    {
      id: 'm6',
      title: 'Tesla stock closes higher than yesterday?',
      description: 'Tesla up 2.3% premarket. New quarterly deliveries report due this week amid EV demand concerns.',
      type: 'binary',
      category: 'finance',
      closeTime: now + 7 * H,
      yesPool: 11_200,
      noPool: 10_800,
      outcome: null,
      predeterminedOutcome: 'yes',
      status: 'open',
      aiPrediction: 0.51,
      resolvedAt: null,
    },
    {
      id: 'm7',
      title: 'Real Madrid to qualify from Champions League group?',
      description: 'Real Madrid need just a point from their final group match to advance. Currently 2nd in the table.',
      type: 'binary',
      category: 'sports',
      closeTime: now + 12 * H,
      yesPool: 15_600,
      noPool: 5_400,
      outcome: null,
      predeterminedOutcome: 'yes',
      status: 'open',
      aiPrediction: 0.74,
      resolvedAt: null,
    },
    {
      id: 'm8',
      title: 'Delhi max temperature exceeds 34°C tomorrow?',
      description: 'Heatwave advisory active for the NCR region. Summer temperatures have been trending above seasonal averages.',
      type: 'binary',
      category: 'weather',
      closeTime: now + 24 * H,
      yesPool: 6_800,
      noPool: 3_200,
      outcome: null,
      predeterminedOutcome: 'yes',
      status: 'open',
      aiPrediction: 0.68,
      resolvedAt: null,
    },
    {
      id: 'm9',
      title: 'Ethereum gains 3%+ this week?',
      description: 'ETH hovering near $3,800. Spot ETF approval anticipation driving high volatility across altcoins.',
      type: 'binary',
      category: 'finance',
      closeTime: now + 48 * H,
      yesPool: 7_400,
      noPool: 9_600,
      outcome: null,
      predeterminedOutcome: 'no',
      status: 'open',
      aiPrediction: 0.43,
      resolvedAt: null,
    },
    {
      id: 'm10',
      title: 'New Bollywood release crosses ₹80cr opening weekend?',
      description: 'Big-budget action film with A-list cast. Strong advance bookings but limited multiplex slots.',
      type: 'binary',
      category: 'entertainment',
      closeTime: now + 36 * H,
      yesPool: 5_500,
      noPool: 6_500,
      outcome: null,
      predeterminedOutcome: 'no',
      status: 'open',
      aiPrediction: 0.46,
      resolvedAt: null,
    },
    {
      id: 'm11',
      title: '10,000+ predictions made on ToldYa today?',
      description: 'Platform currently at 8,200+ active predictors. Growing 15% week-over-week as word spreads.',
      type: 'binary',
      category: 'platform',
      closeTime: now + 10 * H,
      yesPool: 8_100,
      noPool: 6_900,
      outcome: null,
      predeterminedOutcome: 'yes',
      status: 'open',
      aiPrediction: 0.56,
      resolvedAt: null,
    },
    {
      id: 'm12',
      title: 'New leaderboard record set this week?',
      description: 'Current all-time record: 24,500 coins. Top 3 players are closing in. Who will break it?',
      type: 'binary',
      category: 'platform',
      closeTime: now + 72 * H,
      yesPool: 5_200,
      noPool: 3_800,
      outcome: null,
      predeterminedOutcome: 'yes',
      status: 'open',
      aiPrediction: 0.63,
      resolvedAt: null,
    },
  ];
}

export interface BotEntry {
  username: string;
  coins: number;
  totalProfit: number;
  accuracy: number;
  streak: number;
}

export const BOT_LEADERBOARD: BotEntry[] = [
  { username: 'PredictorPro',  coins: 24_500, totalProfit: 14_500, accuracy: 74, streak: 11 },
  { username: 'MarketWizard',  coins: 19_800, totalProfit: 9_800,  accuracy: 70, streak: 7  },
  { username: 'CryptoOracle',  coins: 17_200, totalProfit: 7_200,  accuracy: 68, streak: 5  },
  { username: 'SportsSage',    coins: 15_900, totalProfit: 5_900,  accuracy: 66, streak: 9  },
  { username: 'BullRun99',     coins: 14_300, totalProfit: 4_300,  accuracy: 63, streak: 3  },
  { username: 'StockHunter',   coins: 13_100, totalProfit: 3_100,  accuracy: 62, streak: 6  },
  { username: 'WeatherMind',   coins: 12_400, totalProfit: 2_400,  accuracy: 60, streak: 2  },
  { username: 'Quant_X',       coins: 11_700, totalProfit: 1_700,  accuracy: 59, streak: 4  },
  { username: 'InfoEdge',      coins: 10_800, totalProfit: 800,    accuracy: 57, streak: 1  },
  { username: 'DataDriven',    coins: 10_200, totalProfit: 200,    accuracy: 55, streak: 0  },
  { username: 'Moonshot',      coins: 9_400,  totalProfit: -600,   accuracy: 52, streak: 2  },
  { username: 'ChaosBet',      coins: 8_700,  totalProfit: -1_300, accuracy: 49, streak: 0  },
  { username: 'GutFeeler',     coins: 7_600,  totalProfit: -2_400, accuracy: 46, streak: 1  },
  { username: 'LuckyDice',     coins: 6_800,  totalProfit: -3_200, accuracy: 44, streak: 0  },
  { username: 'YOLOTrader',    coins: 5_400,  totalProfit: -4_600, accuracy: 41, streak: 0  },
];
